### ISSUE TITLE
searching

### ISSUE THREAD

**Issue by cleesmith** [ekanite/ekanite#18]
I coded a simple ruby program to send logs to ekanited, see: https://gist.github.com/cleesmith/1d87a436023f746549ec
... for testing without rsyslog or syslog-ng 
... maybe useful for others and could be altered to read the logs13k.txt file you provide

Some of the following may be issues for bleve, but I noticed:
* searches only work for exact matches: ```ssh``` won't match ```sshd```
* no wildcard ```ssh*``` searches
* no word stemming: listen, listened, listening or similar
* are time range searches possible?
* is it possible to list the most recent logs, say, in descending order by timestamp
... i.e. a kind of near real time view of what's happening
* instead of ```telnet localhost 9950``` doing a http://localhost:9950/ in the browser lists all logs
* running 2 simultaneous ruby programs sending syslogs takes twice as long: from 20 seconds for one to 50 seconds each for two ... i.e. sometimes logs are sent from multiple sources to a central server, or perhaps ekanite is only intended to receive from a single rsyslog/syslog-ng instance
* is there docs or more details about the folder that is created: ```20151018_0000``` which seems to use 1.2M of space for 40 syslogs ?
* 84,440 logs uses 1G <-- ```du -h 20151018_0000``` ... this just seems like a lot, but I'm not sure ?
```
"ekanite": {"launch": 2015-10-18 15:22:40.011642743 +0000 UTC},
"engine": {"batchIndexed": 285, "batchTimeout": 5, "docsIDsRetrived": 1467, "eventsIndexed": 84440, "queriesRx": 60},
"input": {"tcpBytesRead": 9404505, "tcpConnReadEOF": 1674263446, "tcpConnReadError": 1674263449, "tcpConnections": 5, "tcpEventsRx": 84440, "unparsed": 84440},
```
I work on a lot of projects involving syslogs and intrusion detection (events from Snort/Suricata) so I find ekanite interesting. My future view is to replace elasticsearch with something similar but coded in Go for simpler deployments.
Thanks for your efforts.

**Comment by otoolep** [comment]
Thanks for the feedback @cleesmith 

Most of the issues you raised are due to bleve works, though Ekanite may be able to drive bleve differently. As for time-ranged queries, the system is specifically built to handle them (https://github.com/ekanite/ekanite/issues/13) but it is not fully implemented yet. I need to implement my own parser for interpreting range queries.

As for the disk usage issues, this is due to the way BoltDB (which bleve is built on) works. It allocates a lot of disk upfront (and doubles it every time it decides to allocate more). 1GB is a very large amount, but it should stop with 1GB and store a lot of logs in there. I am going to look into using LevelDB, but this means a less cleaner build since LevelDB is in C.

I didn't know about `http://localhost:9950/`! I must see why that happens.

**Comment by cleesmith** [comment]
I will continue testing and pushing syslogs while watching the disk usage -- noticed the shards were allocated in large chunks, so maybe they are mostly empty at first.

Maybe I should spend some more time with Bolt and Bleve just to understand how it all works. I did notice LevelDB, but the pure Go solution is appealing but may be less performant for "big data".

The ```http://localhost:9950``` seemed like an easy way to view the data, well, if it was just the most recent logs that would be even better.
I will close this as the issues are really about bolt/bleve.
Thanks.
